program SIDomper;

uses
  Vcl.Dialogs,
  System.SysUtils,
  Vcl.Forms,
  uMenuPrincipal in 'uMenuPrincipal.pas' {frmMenuPrincipal},
  uGrade in 'Global\uGrade.pas',
  uBaseCadastro in 'Padrao\uBaseCadastro.pas' {frmBaseCadastro},
  uDM in 'Global\uDM.pas' {DM: TDataModule},
  uDMStatus in 'Model\uDMStatus.pas' {DMStatus: TDataModule},
  uUsuario in 'View\uUsuario.pas' {frmUsuario},
  uRegras in 'Global\uRegras.pas',
  uEnumerador in '..\Comum\uEnumerador.pas',
  uUsuarioController in 'Controller\uUsuarioController.pas',
  uDMBase in 'Padrao\uDMBase.pas' {DMBase: TDataModule},
  uDMUsuario in 'Model\uDMUsuario.pas' {DMUsuario: TDataModule},
  uDepartamentoController in 'Controller\uDepartamentoController.pas',
  uDepartamento in 'View\uDepartamento.pas' {frmDepartamento},
  uDMDepartamento in 'Model\uDMDepartamento.pas' {DMDepartamento: TDataModule},
  uImagens in 'View\uImagens.pas' {frmImagens},
  uFormaPagtoController in 'Controller\uFormaPagtoController.pas',
  uOrcamento in 'View\uOrcamento.pas' {frmOrcamento},
  uDepartamentoAcesso in '..\Comum\uDepartamentoAcesso.pas',
  uDMFormaPagto in 'Model\uDMFormaPagto.pas' {DMFormaPagto: TDataModule},
  uModuloController in 'Controller\uModuloController.pas',
  uCidade in 'View\uCidade.pas' {frmCidade},
  uDMModulo in 'Model\uDMModulo.pas' {DMModulo: TDataModule},
  uOrcamentoController in 'Controller\uOrcamentoController.pas',
  uStatus in 'View\uStatus.pas' {frmStatus},
  uStatusController in 'Controller\uStatusController.pas',
  uCliente in 'View\uCliente.pas' {frmCliente},
  uDMParametros in 'Model\uDMParametros.pas' {DMParametros: TDataModule},
  uProspectController in 'Controller\uProspectController.pas',
  uDMTipo in 'Model\uDMTipo.pas' {DMTipo: TDataModule},
  uTipo in 'View\uTipo.pas' {frmTipo},
  uDMCliente in 'Model\uDMCliente.pas' {DMCliente: TDataModule},
  uClienteEspecificacaoController in 'Controller\uClienteEspecificacaoController.pas',
  uClienteEspecificacao in 'View\uClienteEspecificacao.pas' {frmClienteEspecificacao},
  uDMClienteEspecificacao in 'Model\uDMClienteEspecificacao.pas' {DMClienteEspecificacao: TDataModule},
  uVersaoController in 'Controller\uVersaoController.pas',
  uDMClienteModulo in 'Model\uDMClienteModulo.pas' {DMClienteModulo: TDataModule},
  uClienteModuloController in 'Controller\uClienteModuloController.pas',
  uDMClienteEmail in 'Model\uDMClienteEmail.pas' {DMClienteEmail: TDataModule},
  uClienteEmailController in 'Controller\uClienteEmailController.pas',
  uLogin in 'View\uLogin.pas' {frmLogin},
  uConfig in '..\Comum\uConfig.pas',
  uWeb in 'View\uWeb.pas' {frmWeb},
  uSolicitacao in 'View\uSolicitacao.pas' {frmSolicitacao},
  uDMSolicitacao in 'Model\uDMSolicitacao.pas' {DMSolicitacao: TDataModule},
  uParametrosController in 'Controller\uParametrosController.pas',
  uBaseConh in 'View\uBaseConh.pas' {frmBaseConh},
  uProdutoVO in '..\Comum\uProdutoVO.pas',
  uClienteModuloVO in '..\Comum\uClienteModuloVO.pas',
  uFiltroSolicitacao in '..\Comum\uFiltroSolicitacao.pas',
  uFraProspect in 'View\uFraProspect.pas' {FraProspect: TFrame},
  uFraDepartamento in 'View\uFraDepartamento.pas' {FraDepartamento: TFrame},
  uFraDesenv in 'View\uFraDesenv.pas' {FraDesenvolvedor: TFrame},
  uFraOperador in 'View\uFraOperador.pas' {FraOperador: TFrame},
  uFraRevenda in 'View\uFraRevenda.pas' {FraRevenda: TFrame},
  uFiltroCliente in '..\Comum\uFiltroCliente.pas',
  uFraColaborador in 'View\uFraColaborador.pas' {FraColaborador: TFrame},
  uDMVisita in 'Model\uDMVisita.pas' {DMVisita: TDataModule},
  uSolicitacaoController in 'Controller\uSolicitacaoController.pas',
  uParametros in 'View\uParametros.pas' {frmParametros},
  uDMBaseConh in 'Model\uDMBaseConh.pas' {DMBaseConh: TDataModule},
  uFiltroVisita in '..\Comum\uFiltroVisita.pas',
  uChamadoController in 'Controller\uChamadoController.pas',
  uFiltroBaseConhecimento in '..\Comum\uFiltroBaseConhecimento.pas',
  uVersao in 'View\uVersao.pas' {frmVersao},
  uDMVersao in 'Model\uDMVersao.pas' {DMVersao: TDataModule},
  uContaEmailController in 'Controller\uContaEmailController.pas',
  uContaEmail in 'View\uContaEmail.pas' {frmContaEmail},
  uBaseConhController in 'Controller\uBaseConhController.pas',
  uDMChamado in 'Model\uDMChamado.pas' {DMChamado: TDataModule},
  uChamado in 'View\uChamado.pas' {frmChamado},
  uFiltroVersao in '..\Comum\uFiltroVersao.pas',
  uVisitaController in 'Controller\uVisitaController.pas',
  uFiltroChamado in '..\Comum\uFiltroChamado.pas',
  uVisita in 'View\uVisita.pas' {frmVisita},
  uDMEscala in 'Model\uDMEscala.pas' {DMEscala: TDataModule},
  uSolicitacaoStatusVO in '..\Comum\uSolicitacaoStatusVO.pas',
  uBackup in 'View\uBackup.pas' {frmBackup},
  uUtilitarioController in 'Controller\uUtilitarioController.pas',
  uDMRelAtividade in 'Relatorios\uDMRelAtividade.pas' {DMRelAtividade: TDataModule},
  uRevendaVO in '..\Comum\uRevendaVO.pas',
  uPosicaoBotao in 'Controller\uPosicaoBotao.pas',
  uDMRelVisita in 'Model\uDMRelVisita.pas' {DMRelVisita: TDataModule},
  uStatusTroca in 'View\uStatusTroca.pas' {frmStatusTroca},
  uQuadro2 in 'View\uQuadro2.pas' {frmQuadro2},
  uChamadoModulos in 'View\uChamadoModulos.pas' {frmChamadoModulos},
  UInstrucaoSQL in 'View\UInstrucaoSQL.pas' {frmInstrucaoSQL},
  uDMUtilitario in 'Model\uDMUtilitario.pas' {DMUtilitario: TDataModule},
  Vcl.RecError in 'Model\Vcl.RecError.pas' {ReconcileErrorForm},
  uFiltroUsuario in '..\Comum\uFiltroUsuario.pas',
  uListaProblemaChamado in 'View\uListaProblemaChamado.pas' {frmListaProblemaChamado},
  uUsuarioSenha in 'View\uUsuarioSenha.pas' {frmUsuarioSenha},
  uUsuarioPermissaoController in 'Controller\uUsuarioPermissaoController.pas',
  uSolicitacaoDetalhes in 'View\uSolicitacaoDetalhes.pas' {frmSolicitacaoDetalhes},
  uErro in 'View\uErro.pas' {frmErro},
  uArquivosLog in 'View\uArquivosLog.pas' {frmArquivosLog},
  uEnviarEmail in '..\Comum\uEnviarEmail.pas',
  uTelaEnviarEmail in 'View\uTelaEnviarEmail.pas' {frmTelaEnviarEmail},
  uTrocaSenha in 'View\uTrocaSenha.pas' {frmTrocaSenha},
  uChamadoDetalhes in 'View\uChamadoDetalhes.pas' {frmChamadoDetalhes},
  uEmailChamado in 'Outros\uEmailChamado.pas',
  uEmailBase in '..\Comum\uEmailBase.pas',
  uEmailModelo2 in 'Outros\uEmailModelo2.pas',
  uDMContaEmail in 'Model\uDMContaEmail.pas' {DMContaEmail: TDataModule},
  uEscalaController in 'Controller\uEscalaController.pas',
  uRevenda in 'View\uRevenda.pas' {frmRevenda},
  uEmailSolicitacao in 'Outros\uEmailSolicitacao.pas',
  uFormProcesso in 'View\uFormProcesso.pas' {frmProcesso},
  uFuncoesSIDomper in 'Global\uFuncoesSIDomper.pas',
  uEmailVisita in 'Outros\uEmailVisita.pas',
  uEnvioEmailClientes in 'View\uEnvioEmailClientes.pas' {frmEnviarEmailCliente},
  uDMRelChamado in 'Relatorios\uDMRelChamado.pas' {DMRelChamado: TDataModule},
  uModuloVO in '..\Comum\uModuloVO.pas',
  uChamadoColaborador in 'View\uChamadoColaborador.pas' {frmChamadoColaborador},
  uChamadoColaboradorVO in '..\Comum\uChamadoColaboradorVO.pas',
  uChamadoColaboradorController in 'Controller\uChamadoColaboradorController.pas',
  uListaAnexos in 'View\uListaAnexos.pas' {frmListaAnexos},
  uDMAgendamento in 'Model\uDMAgendamento.pas' {dmAgendamento: TDataModule},
  uAgendamentoController in 'Controller\uAgendamentoController.pas',
  uAgendamento in 'View\uAgendamento.pas' {frmAgendamento},
  uAgendamentoVO in '..\Comum\uAgendamentoVO.pas',
  uFiltroAgendamento in '..\Comum\uFiltroAgendamento.pas',
  uAgendamentoMotivo in 'View\uAgendamentoMotivo.pas' {frmAgendamentoMotivo},
  uEmailAgendamento in 'Outros\uEmailAgendamento.pas',
  uPlanoBackup in 'View\uPlanoBackup.pas' {frmPlanoBackup},
  uDMPlanoBackup in 'Model\uDMPlanoBackup.pas' {dmPlanoBackup: TDataModule},
  uPlanoBackupController in 'Controller\uPlanoBackupController.pas',
  uPlanoBackupVO in '..\Comum\uPlanoBackupVO.pas',
  Vcl.Themes,
  Vcl.Styles,
  uFiltroSolucao in 'View\uFiltroSolucao.pas' {frmFiltroSolucao},
  uChamadoGrafico1 in 'View\uChamadoGrafico1.pas' {frmChamadoGrafico1},
  uFormatacaoMemo in 'Global\uFormatacaoMemo.pas',
  uFormatarTexto in 'View\uFormatarTexto.pas' {frmFormatarTexto},
  uSolicitacaoDetalhes2 in 'View\uSolicitacaoDetalhes2.pas' {frmSolicitacaoDetalhes2},
  uDMProspect in 'Model\uDMProspect.pas' {DMProspect: TDataModule},
  uClienteController in 'Controller\uClienteController.pas',
  uProspectVO in '..\Comum\uProspectVO.pas',
  uProspect in 'View\uProspect.pas' {frmProspect},
  uFiltroProspect in '..\Comum\uFiltroProspect.pas',
  uProspectEmailVO in '..\Comum\uProspectEmailVO.pas',
  uChamadoDetalhes2 in 'View\uChamadoDetalhes2.pas' {frmChamadoDetalhes2},
  uOrcamentoVO in '..\Comum\uOrcamentoVO.pas',
  uOrcamentoItemVO in '..\Comum\uOrcamentoItemVO.pas',
  uOrcamentoItemModuloVO in '..\Comum\uOrcamentoItemModuloVO.pas',
  uOrcamentoOcorrenciaVO in '..\Comum\uOrcamentoOcorrenciaVO.pas',
  uOrcamentoVectoVO in '..\Comum\uOrcamentoVectoVO.pas',
  uDMOrcamento in 'Model\uDMOrcamento.pas' {DMOrcamento: TDataModule},
  uTipoController in 'Controller\uTipoController.pas',
  uFiltroOrcamento in '..\Comum\uFiltroOrcamento.pas',
  uRamal in 'View\uRamal.pas' {frmRamal},
  uBaseDetalhes in 'Padrao\uBaseDetalhes.pas' {frmBaseDetalhes},
  uOrcamentoDetalhes in 'View\uOrcamentoDetalhes.pas' {frmOrcamentoDetalhe},
  uParcelas in '..\Comum\uParcelas.pas',
  uChamadoVO in '..\Comum\uChamadoVO.pas',
  uChamadoOcorrenciaVO in '..\Comum\uChamadoOcorrenciaVO.pas',
  uChamadoStatusVO in '..\Comum\uChamadoStatusVO.pas',
  uUsuarioVO in '..\Comum\uUsuarioVO.pas',
  uDMRelVersao in 'Relatorios\uDMRelVersao.pas' {DMRelVersao: TDataModule},
  uDMModeloRelatorio in 'Model\uDMModeloRelatorio.pas' {DMModeloRelatorio: TDataModule},
  uModeloRelatorioController in 'Controller\uModeloRelatorioController.pas',
  uObservacaoVO in '..\Comum\uObservacaoVO.pas',
  uFormaPagto in 'View\uFormaPagto.pas' {frmFormaPagto},
  uDMObservacao in 'Model\uDMObservacao.pas' {DMObservacao: TDataModule},
  uRamalController in 'Controller\uRamalController.pas',
  uFormaPagtoVO in '..\Comum\uFormaPagtoVO.pas',
  uFormaPagtoItemVO in '..\Comum\uFormaPagtoItemVO.pas',
  uRecado in 'View\uRecado.pas' {frmRecado},
  uDMProduto in 'Model\uDMProduto.pas' {DMProduto: TDataModule},
  uModeloRelatorioVO in '..\Comum\uModeloRelatorioVO.pas',
  uRecadoController in 'Controller\uRecadoController.pas',
  uObservacao in 'View\uObservacao.pas' {frmObservacao},
  uOrcamentoImpressao in 'View\uOrcamentoImpressao.pas' {frmOrcamentoImpressao},
  uQuadro in 'View\uQuadro.pas' {frmQuadro},
  uContaEmailVO in '..\Comum\uContaEmailVO.pas',
  uDepartamentoEmailVO in '..\Comum\uDepartamentoEmailVO.pas',
  uDepartamentoAcessoVO in '..\Comum\uDepartamentoAcessoVO.pas',
  uDepartamentoVO in '..\Comum\uDepartamentoVO.pas',
  uClienteVO in '..\Comum\uClienteVO.pas',
  uClienteEmailVO in '..\Comum\uClienteEmailVO.pas',
  uOrcamentoEmailVO in '..\Comum\uOrcamentoEmailVO.pas',
  uKeyField in '..\Comum\DAO\uKeyField.pas',
  uTableName in '..\Comum\DAO\uTableName.pas',
  uConverter in '..\Comum\uConverter.pas',
  uExtensoValor in '..\Comum\uExtensoValor.pas',
  uEstiloTelas in 'View\uEstiloTelas.pas' {frmEstiloTelas},
  uObservacaoEmail in 'View\uObservacaoEmail.pas' {frmObservacaoEmail},
  uGenericProperty in 'Global\uGenericProperty.pas',
  uTelaAbertura in 'View\uTelaAbertura.pas' {frmTelaAbertura},
  uDMRamal in 'Model\uDMRamal.pas' {dmRamal: TDataModule},
  uFeriadoController in 'Controller\uFeriadoController.pas',
  uModeloRelatorio in 'View\uModeloRelatorio.pas' {frmModeloRelatorio},
  uRamalVO in '..\Comum\uRamalVO.pas',
  uRamalItensVO in '..\Comum\uRamalItensVO.pas',
  uListaRamal in 'View\uListaRamal.pas' {frmListaRamal},
  uFraTipo in 'View\uFraTipo.pas' {FraTipo: TFrame},
  uTipoVO in '..\Comum\uTipoVO.pas',
  uOrcamentoNaoAprovadoVO in '..\Comum\uOrcamentoNaoAprovadoVO.pas',
  uOrcamentoNAprovadoController in 'Controller\uOrcamentoNAprovadoController.pas',
  uOrcamentoNAprovado in 'View\uOrcamentoNAprovado.pas' {frmOrcamentoNAprovado},
  uCategoriaController in 'Controller\uCategoriaController.pas',
  uRecadoVO in '..\Comum\uRecadoVO.pas',
  uStatusVO in '..\Comum\uStatusVO.pas',
  uRecadoFiltro in '..\Comum\uRecadoFiltro.pas',
  uEscala in 'View\uEscala.pas' {frmEscala},
  uFraStatus in 'View\uFraStatus.pas' {FraStatus: TFrame},
  uFraVersao in 'View\uFraVersao.pas' {FraVersao: TFrame},
  uSolicitacaoTempoVO in '..\Comum\uSolicitacaoTempoVO.pas',
  uConferenciaTempoGeral in 'View\uConferenciaTempoGeral.pas' {frmConferenciaTempoGeral},
  uDMRelSolicitacao in 'Model\uDMRelSolicitacao.pas' {DMRelSolicitacao: TDataModule},
  uFraAnalista in 'View\uFraAnalista.pas' {FraAnalista: TFrame},
  uSolicitacaoVO in '..\Comum\uSolicitacaoVO.pas',
  uBaseConhDetalhe in 'View\uBaseConhDetalhe.pas' {frmBaseConhDetalhe},
  uSolicitacaoTempoManual in 'View\uSolicitacaoTempoManual.pas' {frmSolicitacaoTempoManual},
  uDMRelUsuario in 'Relatorios\uDMRelUsuario.pas' {DMRelUsuario: TDataModule},
  uConferenciaTempo in 'View\uConferenciaTempo.pas' {frmConferenciaTempo},
  uDMRecado in 'Model\uDMRecado.pas' {DMRecado: TDataModule},
  uDMRevenda in 'Model\uDMRevenda.pas' {DMRevenda: TDataModule},
  uRevendaController in 'Controller\uRevendaController.pas',
  uFeriado in 'View\uFeriado.pas' {frmFeriado},
  uEscalaVO in '..\Comum\uEscalaVO.pas',
  uFraUsuario in 'View\uFraUsuario.pas' {FraUsuario: TFrame},
  uDMRelEscala in 'Relatorios\uDMRelEscala.pas' {DMRelEscala: TDataModule},
  uDMCidade in 'Model\uDMCidade.pas' {DMCidade: TDataModule},
  uObsevacaoController in 'Controller\uObsevacaoController.pas',
  uModulo in 'View\uModulo.pas' {frmModulo},
  uCidadeVO in '..\Comum\uCidadeVO.pas',
  uFraCliente in 'View\uFraCliente.pas' {FraCliente: TFrame},
  uFraCidade in 'View\uFraCidade.pas' {FraCidade: TFrame},
  uContatoVO in '..\Comum\uContatoVO.pas',
  uContatoController in 'Controller\uContatoController.pas',
  uDMContato in 'Model\uDMContato.pas' {DMContato: TDataModule},
  uLicenca in 'View\uLicenca.pas' {frmLicenca},
  uLicencaController in 'Controller\uLicencaController.pas',
  ULicencaVO in '..\Comum\ULicencaVO.pas',
  uLicencaItensVO in '..\Comum\uLicencaItensVO.pas',
  uFiltroLicenca in '..\Comum\uFiltroLicenca.pas',
  uImportarClientesController in 'Controller\uImportarClientesController.pas',
  uClassValidacao in '..\Comum\uClassValidacao.pas',
  uFraModulo in 'View\uFraModulo.pas' {FraModulo: TFrame},
  uFraCategoria in 'View\uFraCategoria.pas' {FraCategoria: TFrame},
  uDMRelCliente in 'Model\uDMRelCliente.pas' {DMRelCliente: TDataModule},
  uChamadoQuadroViewModel in '..\Comum\ViewModel\uChamadoQuadroViewModel.pas',
  uSolicitacaoViewModel in '..\Comum\ViewModel\uSolicitacaoViewModel.pas',
  uRecadoQuadroViewModel in '..\Comum\ViewModel\uRecadoQuadroViewModel.pas',
  uCidadeController in 'Controller\uCidadeController.pas',
  uDMFeriado in 'Model\uDMFeriado.pas' {DMFeriado: TDataModule},
  uUsuarioPermissaoVO in '..\Comum\uUsuarioPermissaoVO.pas',
  uParametroVO in '..\Comum\uParametroVO.pas',
  uPermissaoSolicitacaoVO in '..\Comum\uPermissaoSolicitacaoVO.pas',
  uPermissaoChamadoVO in '..\Comum\uPermissaoChamadoVO.pas',
  uDMCategoria in 'Model\uDMCategoria.pas' {DMCategoria: TDataModule},
  uProdutoController in 'Controller\uProdutoController.pas',
  uTabPreco in 'View\uTabPreco.pas' {frmTabPreco},
  uFraProduto in 'View\uFraProduto.pas' {FraProduto: TFrame},
  uCategoria in 'View\uCategoria.pas' {frmCategoria},
  uCategoriaVO in '..\Comum\uCategoriaVO.pas',
  uSolicitacaoCronogramaVO in '..\Comum\uSolicitacaoCronogramaVO.pas',
  uSolicitacaoOcorrenciaVO in '..\Comum\uSolicitacaoOcorrenciaVO.pas',
  uTabPrecoController in 'Controller\uTabPrecoController.pas',
  uTabelaPrecoVO in '..\Comum\uTabelaPrecoVO.pas',
  uDMTabPreco in 'Model\uDMTabPreco.pas' {DMTabPreco: TDataModule},
  uProduto in 'View\uProduto.pas' {frmProduto},
  uListaProblemaSolicitacao in 'View\uListaProblemaSolicitacao.pas' {frmListaProblemaSolicitacao},
  uQuadroController in 'Controller\uQuadroController.pas';

{$R *.res}

begin
  Application.Initialize;

  frmTelaAbertura :=TfrmTelaAbertura.Create(nil);
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TfrmMenuPrincipal, frmMenuPrincipal);
  TStyleManager.TrySetStyle(dm.Tema);
  Application.CreateForm(TfrmLogin, frmLogin);
  FreeAndNil(frmTelaAbertura);
  Application.Run;
end.
