unit uDMRelChamado;

interface

uses
  System.SysUtils, System.Classes, uDM, Data.DB, ppDB, ppDBPipe, ppParameter,
  ppDesignLayer, ppBands, ppPrnabl, ppClass, ppCtrls, ppCache, ppComm, ppRelatv,
  ppProd, ppReport, Datasnap.DBClient, ppStrtch, ppSubRpt, ppVar, ppMemo,
  ppRichTx, ppTypes;

type
  TDMRelChamado = class(TDataModule)
    CDSRelChamadoDetModelo1: TClientDataSet;
    RelChamadoModelo1: TppReport;
    ppHeaderBand2: TppHeaderBand;
    ppDetailBand2: TppDetailBand;
    ppDBText4: TppDBText;
    ppDesignLayers2: TppDesignLayers;
    ppDesignLayer2: TppDesignLayer;
    ppParameterList2: TppParameterList;
    dbRelChamadoModelo1: TppDBPipeline;
    dsRelChamadoDetModelo1: TDataSource;
    dsRelChamadoModelo1: TDataSource;
    CDSRelChamadoModelo1: TClientDataSet;
    CDSRelChamadoModelo1Cha_Id: TAutoIncField;
    CDSRelChamadoModelo1Cha_DataAbertura: TDateField;
    CDSRelChamadoModelo1Cha_HoraAbertura: TTimeField;
    CDSRelChamadoModelo1Cha_Contato: TStringField;
    CDSRelChamadoModelo1Cha_Nivel: TIntegerField;
    CDSRelChamadoModelo1Nivel: TStringField;
    CDSRelChamadoModelo1Tip_Nome: TWideStringField;
    CDSRelChamadoModelo1Sta_Nome: TWideStringField;
    CDSRelChamadoModelo1QRelChamadoDetModelo1: TDataSetField;
    CDSRelChamadoModelo1Cli_Codigo: TIntegerField;
    CDSRelChamadoModelo1Cli_Nome: TWideStringField;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppDBText1: TppDBText;
    lblTitulo1: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppLabel7: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppDBText2: TppDBText;
    ppDBText3: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppLine1: TppLine;
    ppLabel11: TppLabel;
    ppDBCalc1: TppDBCalc;
    ppLine2: TppLine;
    ppDBCalc2: TppDBCalc;
    ppLabel12: TppLabel;
    ppSummaryBand1: TppSummaryBand;
    ppLine3: TppLine;
    ppSubReport1: TppSubReport;
    ppChildReport1: TppChildReport;
    dbRelChamadoDetModelo1: TppDBPipeline;
    ppDesignLayers1: TppDesignLayers;
    ppDesignLayer1: TppDesignLayer;
    ppTitleBand1: TppTitleBand;
    ppDetailBand1: TppDetailBand;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLine4: TppLine;
    ppLabel17: TppLabel;
    ppLine5: TppLine;
    ppDBText13: TppDBText;
    ppSummaryBand2: TppSummaryBand;
    CDSRelChamadoModelo1TotalHoraDecimal: TFloatField;
    CDSRelChamadoModelo1TotalHoras: TStringField;
    CDSRelChamadoDetModelo1ChOco_Data: TDateField;
    CDSRelChamadoDetModelo1ChOco_HoraInicio: TTimeField;
    CDSRelChamadoDetModelo1ChOco_HoraFim: TTimeField;
    CDSRelChamadoDetModelo1ChOco_DescricaoSolucao: TStringField;
    CDSRelChamadoDetModelo1Usu_UserName: TWideStringField;
    ppLabel18: TppLabel;
    lblTotalHorasModelo1: TppLabel;
    SumTotalHorasModelo1: TppDBCalc;
    ppLine6: TppLine;
    CDSRelChamadoDetModelo1ChOco_TotalHoras: TFloatField;
    ppLine7: TppLine;
    lblPeriodoModelo1: TppLabel;
    ppDBRichText1: TppDBRichText;
    CDSRelChamadoModelo2: TClientDataSet;
    dsRelChamadoDetModelo2: TDataSource;
    CDSRelChamadoModelo2Cli_Codigo: TIntegerField;
    CDSRelChamadoModelo2Cli_Nome: TWideStringField;
    CDSRelChamadoModelo2Rev_Codigo: TIntegerField;
    CDSRelChamadoModelo2Rev_Nome: TWideStringField;
    CDSRelChamadoModelo2QtdeChamados: TIntegerField;
    dbRelChamadoModelo2: TppDBPipeline;
    RelChamadoModelo2: TppReport;
    ppParameterList1: TppParameterList;
    ppDesignLayers3: TppDesignLayers;
    ppDesignLayer3: TppDesignLayer;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand3: TppDetailBand;
    ppSystemVariable3: TppSystemVariable;
    ppSystemVariable4: TppSystemVariable;
    ppLabel10: TppLabel;
    ppLabel20: TppLabel;
    ppLabel21: TppLabel;
    ppLabel22: TppLabel;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    txtQtdeHorasModelo2: TppDBText;
    lblTotalHorasModelo2: TppLabel;
    ppGroup2: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppGroupFooterBand2: TppGroupFooterBand;
    ppLabel23: TppLabel;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppSummaryBand3: TppSummaryBand;
    ppLine8: TppLine;
    ppLabel24: TppLabel;
    ppDBCalc3: TppDBCalc;
    ppLine9: TppLine;
    ppLabel25: TppLabel;
    sumTotalHorasModelo2: TppDBCalc;
    lblTotalHorasGeralModelo2: TppLabel;
    lblSubTotalHorasModelo2: TppLabel;
    sumSubTotalHorasModelo2: TppDBCalc;
    lblPeriodoModelo2: TppLabel;
    ppDBCalc5: TppDBCalc;
    ppDBCalc4: TppDBCalc;
    ppDBCalc6: TppDBCalc;
    ppShape1: TppShape;
    ppLabel1: TppLabel;
    CDSRelChamadoModelo3: TClientDataSet;
    dsRelChamadoModelo3: TDataSource;
    dbRelChamadoModelo3: TppDBPipeline;
    RelChamadoModelo3: TppReport;
    CDSRelChamadoModelo3Usu_Codigo: TIntegerField;
    CDSRelChamadoModelo3QtdeChamados: TIntegerField;
    CDSRelChamadoModelo3TotalHoras: TFloatField;
    ppParameterList3: TppParameterList;
    ppDesignLayers4: TppDesignLayers;
    ppDesignLayer4: TppDesignLayer;
    ppHeaderBand3: TppHeaderBand;
    ppDetailBand4: TppDetailBand;
    ppLabel26: TppLabel;
    ppSystemVariable5: TppSystemVariable;
    ppSystemVariable6: TppSystemVariable;
    ppLabel28: TppLabel;
    ppLabel29: TppLabel;
    ppLabel30: TppLabel;
    ppSummaryBand4: TppSummaryBand;
    ppLine10: TppLine;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    txtQtdeHorasModelo3: TppDBText;
    lblTotalHorasModelo3: TppLabel;
    ppLabel33: TppLabel;
    ppDBCalc8: TppDBCalc;
    ppDBCalc10: TppDBCalc;
    sumTotalHorasModelo3: TppDBCalc;
    lblTotalHorasGeralModelo3: TppLabel;
    lblPeriodoModelo3: TppLabel;
    CDSRelChamadoModelo4: TClientDataSet;
    dsRelChamadoModelo4: TDataSource;
    dbRelChamadoModelo4: TppDBPipeline;
    RelChamadoModelo4: TppReport;
    CDSRelChamadoModelo4Tip_Codigo: TIntegerField;
    CDSRelChamadoModelo4Tip_Nome: TWideStringField;
    CDSRelChamadoModelo4Rev_Codigo: TIntegerField;
    CDSRelChamadoModelo4Rev_Nome: TWideStringField;
    CDSRelChamadoModelo4QtdeChamados: TIntegerField;
    ppParameterList4: TppParameterList;
    ppDesignLayers5: TppDesignLayers;
    ppDesignLayer5: TppDesignLayer;
    ppHeaderBand4: TppHeaderBand;
    ppDetailBand5: TppDetailBand;
    ppSummaryBand5: TppSummaryBand;
    ppSystemVariable7: TppSystemVariable;
    ppSystemVariable8: TppSystemVariable;
    ppLabel19: TppLabel;
    ppLabel27: TppLabel;
    ppLabel34: TppLabel;
    ppLabel35: TppLabel;
    ppLine12: TppLine;
    ppGroup4: TppGroup;
    ppGroupHeaderBand4: TppGroupHeaderBand;
    ppGroupFooterBand4: TppGroupFooterBand;
    ppLabel36: TppLabel;
    ppDBText24: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppDBText28: TppDBText;
    txtQtdeHorasModelo4: TppDBText;
    lblTotalHorasModelo4: TppLabel;
    ppLabel38: TppLabel;
    ppLabel39: TppLabel;
    ppDBCalc11: TppDBCalc;
    ppDBCalc12: TppDBCalc;
    ppLine13: TppLine;
    lblPeriodoModelo4: TppLabel;
    sumSubTotalHorasModelo41: TppDBCalc;
    lblSubTotalHorasModelo4: TppLabel;
    sumTotalHorasModelo41: TppDBCalc;
    lblTotalHorasGeralModelo4: TppLabel;
    sumSubTotalHorasModelo4: TppDBCalc;
    sumTotalHorasModelo4: TppDBCalc;
    ppShape2: TppShape;
    ppGroup5: TppGroup;
    ppGroupHeaderBand5: TppGroupHeaderBand;
    ppGroupFooterBand5: TppGroupFooterBand;
    CDSRelChamadoModelo3Usu_Nome: TWideStringField;
    CDSRelChamadoModelo4TotalHoras: TFloatField;
    CDSRelChamadoModelo2TotalHoras: TFloatField;
    ppLine11: TppLine;
    CDSRelChamadoModelo3TotalHorasDetalhes: TFloatField;
    CDSRelChamadoModelo3A: TClientDataSet;
    CDSRelChamadoModelo3AUsu_Codigo: TIntegerField;
    CDSRelChamadoModelo3AQtdeChamados: TIntegerField;
    CDSRelChamadoModelo3ATotalHoras: TFloatField;
    CDSRelChamadoModelo3AUsu_Nome: TStringField;
    CDSRelChamadoModelo3ATotalHorasDetalhes: TFloatField;
    ppLabel2: TppLabel;
    sumTotalHorasColabModelo3: TppDBCalc;
    txtQtdeHorasColabModelo3: TppDBText;
    lblTotalHorasColabModelo3: TppLabel;
    lblTotalHorasGeralColabModelo3: TppLabel;
    ppSystemVariable9: TppSystemVariable;
    ppSystemVariable10: TppSystemVariable;
    ppSystemVariable11: TppSystemVariable;
    ppSystemVariable12: TppSystemVariable;
    CDSRelChamadoModelo1TotalHorasGeral: TFloatField;
    ppLabel31: TppLabel;
    somaTotalGeralModel1: TppDBCalc;
    lblTotalGeralModelo1: TppLabel;
    somaTotalGeralModel1A: TppDBCalc;
    ppLabel32: TppLabel;
    lblTotalGeralModelo1A: TppLabel;
    CDSRelChamadoModelo5: TClientDataSet;
    dsRelChamadoModelo5: TDataSource;
    dbRelChamadoModelo5: TppDBPipeline;
    CDSRelChamadoModelo5Cha_DataAbertura: TDateField;
    CDSRelChamadoModelo5QtdeChamados: TIntegerField;
    CDSRelChamadoModelo5TotalHoras: TFloatField;
    CDSRelChamadoModelo6: TClientDataSet;
    CDSRelChamadoModelo6RelCha_Usuario: TIntegerField;
    CDSRelChamadoModelo6RelCha_Revenda: TIntegerField;
    CDSRelChamadoModelo6RelCha_Tipo: TIntegerField;
    CDSRelChamadoModelo6Usu_Codigo: TIntegerField;
    CDSRelChamadoModelo6Usu_Nome: TWideStringField;
    CDSRelChamadoModelo6Rev_Nome: TWideStringField;
    CDSRelChamadoModelo6Tip_Nome: TWideStringField;
    CDSRelChamadoModelo6Mes1: TStringField;
    CDSRelChamadoModelo6Mes2: TStringField;
    CDSRelChamadoModelo6Mes3: TStringField;
    CDSRelChamadoModelo6Mes4: TStringField;
    CDSRelChamadoModelo6Mes5: TStringField;
    CDSRelChamadoModelo6Mes6: TStringField;
    CDSRelChamadoModelo6Mes7: TStringField;
    CDSRelChamadoModelo6Mes8: TStringField;
    CDSRelChamadoModelo6Mes9: TStringField;
    CDSRelChamadoModelo6Mes10: TStringField;
    CDSRelChamadoModelo6Mes11: TStringField;
    CDSRelChamadoModelo6Mes12: TStringField;
    CDSRelChamadoModelo6Valor1: TCurrencyField;
    CDSRelChamadoModelo6Valor3: TCurrencyField;
    CDSRelChamadoModelo6Valor4: TCurrencyField;
    CDSRelChamadoModelo6Valor5: TCurrencyField;
    CDSRelChamadoModelo6Valor6: TCurrencyField;
    CDSRelChamadoModelo6Valor7: TCurrencyField;
    CDSRelChamadoModelo6Valor8: TCurrencyField;
    CDSRelChamadoModelo6Valor9: TCurrencyField;
    CDSRelChamadoModelo6Valor10: TCurrencyField;
    CDSRelChamadoModelo6Valor11: TCurrencyField;
    CDSRelChamadoModelo6Valor12: TCurrencyField;
    CDSRelChamadoModelo6Qtde1: TIntegerField;
    CDSRelChamadoModelo6Qtde2: TIntegerField;
    CDSRelChamadoModelo6Qtde3: TIntegerField;
    CDSRelChamadoModelo6Qtde4: TIntegerField;
    CDSRelChamadoModelo6Qtde5: TIntegerField;
    CDSRelChamadoModelo6Qtde6: TIntegerField;
    CDSRelChamadoModelo6Qtde7: TIntegerField;
    CDSRelChamadoModelo6Qtde8: TIntegerField;
    CDSRelChamadoModelo6Qtde9: TIntegerField;
    CDSRelChamadoModelo6Qtde10: TIntegerField;
    CDSRelChamadoModelo6Qtde11: TIntegerField;
    CDSRelChamadoModelo6Qtde12: TIntegerField;
    CDSRelChamadoModelo6Horas1: TFloatField;
    CDSRelChamadoModelo6Horas2: TFloatField;
    CDSRelChamadoModelo6Horas3: TFloatField;
    CDSRelChamadoModelo6Horas4: TFloatField;
    CDSRelChamadoModelo6Horas5: TFloatField;
    CDSRelChamadoModelo6Horas6: TFloatField;
    CDSRelChamadoModelo6Horas7: TFloatField;
    CDSRelChamadoModelo6Horas8: TFloatField;
    CDSRelChamadoModelo6Horas9: TFloatField;
    CDSRelChamadoModelo6Horas10: TFloatField;
    CDSRelChamadoModelo6Horas11: TFloatField;
    CDSRelChamadoModelo6Horas12: TFloatField;
    dbRelChamadoModelo6: TppDBPipeline;
    RelChamadoModelo6: TppReport;
    dsRelChamadoModelo6: TDataSource;
    ppParameterList5: TppParameterList;
    ppDesignLayers6: TppDesignLayers;
    ppDesignLayer6: TppDesignLayer;
    ppHeaderBand5: TppHeaderBand;
    ppDetailBand6: TppDetailBand;
    ppLabel37: TppLabel;
    ppDBText23: TppDBText;
    ppDBText29: TppDBText;
    ppLabel41: TppLabel;
    ppLabel44: TppLabel;
    ppDBText30: TppDBText;
    CDSRelChamadoModelo6CTotalHoras1: TStringField;
    CDSRelChamadoModelo6CTotalHoras2: TStringField;
    CDSRelChamadoModelo6CTotalHoras3: TStringField;
    CDSRelChamadoModelo6CTotalHoras4: TStringField;
    CDSRelChamadoModelo6CTotalHoras5: TStringField;
    CDSRelChamadoModelo6CTotalHoras6: TStringField;
    CDSRelChamadoModelo6CTotalHoras7: TStringField;
    CDSRelChamadoModelo6CTotalHoras8: TStringField;
    CDSRelChamadoModelo6CTotalHoras9: TStringField;
    CDSRelChamadoModelo6CTotalHoras10: TStringField;
    CDSRelChamadoModelo6CTotalHoras11: TStringField;
    CDSRelChamadoModelo6CTotalHoras12: TStringField;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppLabel45: TppLabel;
    ppLabel47: TppLabel;
    ppDBText33: TppDBText;
    ppDBText34: TppDBText;
    ppLine14: TppLine;
    ppLine15: TppLine;
    ppDBText35: TppDBText;
    ppLabel49: TppLabel;
    ppLabel52: TppLabel;
    ppLine16: TppLine;
    ppDBText36: TppDBText;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppLabel53: TppLabel;
    ppLabel56: TppLabel;
    ppLine17: TppLine;
    ppDBText39: TppDBText;
    ppDBText40: TppDBText;
    ppDBText41: TppDBText;
    ppLabel40: TppLabel;
    ppLabel59: TppLabel;
    ppLine18: TppLine;
    ppDBText42: TppDBText;
    ppDBText43: TppDBText;
    ppDBText44: TppDBText;
    ppLabel60: TppLabel;
    ppLabel63: TppLabel;
    ppLine19: TppLine;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppSummaryBand6: TppSummaryBand;
    lblTitulo06: TppLabel;
    ppSystemVariable13: TppSystemVariable;
    ppSystemVariable14: TppSystemVariable;
    ppSystemVariable15: TppSystemVariable;
    ppLine20: TppLine;
    ppDBText22: TppDBText;
    ppLabel42: TppLabel;
    ppLabel43: TppLabel;
    ppLine21: TppLine;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppDBText47: TppDBText;
    ppLabel46: TppLabel;
    ppLabel48: TppLabel;
    ppLine22: TppLine;
    ppDBText48: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppLabel50: TppLabel;
    ppLabel51: TppLabel;
    ppLine23: TppLine;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText55: TppDBText;
    ppLabel54: TppLabel;
    ppLabel55: TppLabel;
    ppLine24: TppLine;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText58: TppDBText;
    ppLabel57: TppLabel;
    ppLabel58: TppLabel;
    ppLine25: TppLine;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppDBText61: TppDBText;
    ppLabel61: TppLabel;
    ppLabel62: TppLabel;
    ppLine26: TppLine;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppDBText64: TppDBText;
    ppGroup3: TppGroup;
    ppGroupHeaderBand3: TppGroupHeaderBand;
    ppGroupFooterBand3: TppGroupFooterBand;
    ppLabel65: TppLabel;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppLine27: TppLine;
    lblRelatorio06: TppLabel;
    RelChamadoModelo7: TppReport;
    ppHeaderBand6: TppHeaderBand;
    ppLabel64: TppLabel;
    ppDBText67: TppDBText;
    ppLabel66: TppLabel;
    ppLabel67: TppLabel;
    ppDBText68: TppDBText;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppLine28: TppLine;
    ppLine29: TppLine;
    ppDBText69: TppDBText;
    ppLabel70: TppLabel;
    ppLabel71: TppLabel;
    ppLine30: TppLine;
    ppDBText70: TppDBText;
    ppLabel72: TppLabel;
    ppLabel73: TppLabel;
    ppLine31: TppLine;
    ppDBText71: TppDBText;
    ppLabel74: TppLabel;
    ppLabel75: TppLabel;
    ppLine32: TppLine;
    ppDBText72: TppDBText;
    ppLabel76: TppLabel;
    ppLabel77: TppLabel;
    ppLine33: TppLine;
    lblTituloRelatorio7: TppLabel;
    ppSystemVariable16: TppSystemVariable;
    ppSystemVariable17: TppSystemVariable;
    ppSystemVariable18: TppSystemVariable;
    ppDBText73: TppDBText;
    ppLabel79: TppLabel;
    ppLabel80: TppLabel;
    ppLine34: TppLine;
    ppDBText74: TppDBText;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLine35: TppLine;
    ppDBText75: TppDBText;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLine36: TppLine;
    ppDBText76: TppDBText;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppLine37: TppLine;
    ppDBText77: TppDBText;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLine38: TppLine;
    ppDBText78: TppDBText;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppLine39: TppLine;
    ppLine40: TppLine;
    lblRelatorio07: TppLabel;
    ppDetailBand7: TppDetailBand;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppDBText81: TppDBText;
    ppDBText82: TppDBText;
    ppDBText83: TppDBText;
    ppDBText84: TppDBText;
    ppDBText85: TppDBText;
    ppDBText86: TppDBText;
    ppDBText89: TppDBText;
    ppDBText90: TppDBText;
    ppDBText91: TppDBText;
    ppDBText92: TppDBText;
    ppDBText93: TppDBText;
    ppDBText94: TppDBText;
    ppDBText95: TppDBText;
    ppDBText96: TppDBText;
    ppDBText97: TppDBText;
    ppDBText98: TppDBText;
    ppDBText99: TppDBText;
    ppDBText100: TppDBText;
    ppDBText101: TppDBText;
    ppDBText103: TppDBText;
    ppDBText104: TppDBText;
    ppSummaryBand7: TppSummaryBand;
    ppDesignLayers7: TppDesignLayers;
    ppDesignLayer7: TppDesignLayer;
    ppParameterList6: TppParameterList;
    ppDBText108: TppDBText;
    ppDBText109: TppDBText;
    ppGroup6: TppGroup;
    ppGroupHeaderBand6: TppGroupHeaderBand;
    ppGroupFooterBand6: TppGroupFooterBand;
    ppDBText116: TppDBText;
    CDSRelChamadoModelo6CHorasB1: TStringField;
    CDSRelChamadoModelo6CHorasB2: TStringField;
    CDSRelChamadoModelo6CHorasB3: TStringField;
    CDSRelChamadoModelo6CHorasB4: TStringField;
    CDSRelChamadoModelo6CHorasB5: TStringField;
    CDSRelChamadoModelo6CHorasB6: TStringField;
    CDSRelChamadoModelo6CHorasB7: TStringField;
    CDSRelChamadoModelo6CHorasB8: TStringField;
    CDSRelChamadoModelo6CHorasB9: TStringField;
    CDSRelChamadoModelo6CHorasB10: TStringField;
    CDSRelChamadoModelo6CHorasB11: TStringField;
    CDSRelChamadoModelo6CHorasB12: TStringField;
    ppLine41: TppLine;
    RelVisitaModelo5: TppReport;
    ppHeaderBand7: TppHeaderBand;
    ppDBText117: TppDBText;
    ppLabel78: TppLabel;
    ppLabel91: TppLabel;
    ppDBText118: TppDBText;
    ppLabel104: TppLabel;
    ppLabel105: TppLabel;
    ppLine42: TppLine;
    ppLine43: TppLine;
    ppDBText119: TppDBText;
    ppLabel106: TppLabel;
    ppLabel107: TppLabel;
    ppLine44: TppLine;
    ppDBText120: TppDBText;
    ppLabel108: TppLabel;
    ppLabel109: TppLabel;
    ppLine45: TppLine;
    ppLabel110: TppLabel;
    ppSystemVariable19: TppSystemVariable;
    ppSystemVariable20: TppSystemVariable;
    ppSystemVariable21: TppSystemVariable;
    ppLine46: TppLine;
    lblRelatorioVisita5: TppLabel;
    ppDBText121: TppDBText;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ppLine47: TppLine;
    ppDBText122: TppDBText;
    ppLabel119: TppLabel;
    ppLabel120: TppLabel;
    ppLine48: TppLine;
    ppDBText123: TppDBText;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLine49: TppLine;
    ppDBText124: TppDBText;
    ppLabel125: TppLabel;
    ppLabel126: TppLabel;
    ppLine50: TppLine;
    ppDBText125: TppDBText;
    ppLabel128: TppLabel;
    ppLabel129: TppLabel;
    ppLine51: TppLine;
    ppDBText126: TppDBText;
    ppLabel131: TppLabel;
    ppLabel132: TppLabel;
    ppLine52: TppLine;
    ppDBText127: TppDBText;
    ppLabel134: TppLabel;
    ppLabel135: TppLabel;
    ppLine53: TppLine;
    ppDBText128: TppDBText;
    ppLabel137: TppLabel;
    ppLabel138: TppLabel;
    ppLine54: TppLine;
    ppDetailBand8: TppDetailBand;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText131: TppDBText;
    ppDBText132: TppDBText;
    ppDBText133: TppDBText;
    ppDBText134: TppDBText;
    ppDBText135: TppDBText;
    ppDBText136: TppDBText;
    ppDBText141: TppDBText;
    ppDBText142: TppDBText;
    ppDBText144: TppDBText;
    ppDBText145: TppDBText;
    ppDBText147: TppDBText;
    ppDBText148: TppDBText;
    ppDBText150: TppDBText;
    ppDBText151: TppDBText;
    ppDBText153: TppDBText;
    ppDBText154: TppDBText;
    ppDBText156: TppDBText;
    ppDBText157: TppDBText;
    ppDBText159: TppDBText;
    ppDBText160: TppDBText;
    ppDBText162: TppDBText;
    ppDBText163: TppDBText;
    ppSummaryBand8: TppSummaryBand;
    ppGroup7: TppGroup;
    ppGroupHeaderBand7: TppGroupHeaderBand;
    ppLabel140: TppLabel;
    ppDBText165: TppDBText;
    ppDBText166: TppDBText;
    ppGroupFooterBand7: TppGroupFooterBand;
    ppLine55: TppLine;
    ppDesignLayers8: TppDesignLayers;
    ppDesignLayer8: TppDesignLayer;
    ppParameterList7: TppParameterList;
    CDSRelChamadoModelo6Valor2: TCurrencyField;
    RelVisitaModelo6: TppReport;
    ppHeaderBand8: TppHeaderBand;
    ppDBText167: TppDBText;
    ppLabel111: TppLabel;
    ppLabel141: TppLabel;
    ppDBText168: TppDBText;
    ppLabel142: TppLabel;
    ppLabel143: TppLabel;
    ppLine56: TppLine;
    ppLine57: TppLine;
    ppDBText169: TppDBText;
    ppLabel144: TppLabel;
    ppLabel145: TppLabel;
    ppLine58: TppLine;
    ppDBText170: TppDBText;
    ppLabel146: TppLabel;
    ppLabel147: TppLabel;
    ppLine59: TppLine;
    ppLabel148: TppLabel;
    ppSystemVariable22: TppSystemVariable;
    ppSystemVariable23: TppSystemVariable;
    ppSystemVariable24: TppSystemVariable;
    ppLine60: TppLine;
    lblRelatorioVisita6: TppLabel;
    ppDBText171: TppDBText;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppLine61: TppLine;
    ppDBText172: TppDBText;
    ppLabel157: TppLabel;
    ppLabel158: TppLabel;
    ppLine62: TppLine;
    ppDBText173: TppDBText;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppLine63: TppLine;
    ppDBText174: TppDBText;
    ppLabel163: TppLabel;
    ppLabel164: TppLabel;
    ppLine64: TppLine;
    ppDBText175: TppDBText;
    ppLabel166: TppLabel;
    ppLabel167: TppLabel;
    ppLine65: TppLine;
    ppDBText176: TppDBText;
    ppLabel169: TppLabel;
    ppLabel170: TppLabel;
    ppLine66: TppLine;
    ppDBText177: TppDBText;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppLine67: TppLine;
    ppDBText178: TppDBText;
    ppLabel175: TppLabel;
    ppLabel176: TppLabel;
    ppLine68: TppLine;
    ppDetailBand9: TppDetailBand;
    ppDBText179: TppDBText;
    ppDBText180: TppDBText;
    ppDBText181: TppDBText;
    ppDBText182: TppDBText;
    ppDBText183: TppDBText;
    ppDBText184: TppDBText;
    ppDBText185: TppDBText;
    ppDBText186: TppDBText;
    ppDBText191: TppDBText;
    ppDBText192: TppDBText;
    ppDBText194: TppDBText;
    ppDBText195: TppDBText;
    ppDBText197: TppDBText;
    ppDBText198: TppDBText;
    ppDBText200: TppDBText;
    ppDBText201: TppDBText;
    ppDBText203: TppDBText;
    ppDBText204: TppDBText;
    ppDBText206: TppDBText;
    ppDBText207: TppDBText;
    ppDBText209: TppDBText;
    ppDBText210: TppDBText;
    ppDBText212: TppDBText;
    ppDBText213: TppDBText;
    ppSummaryBand9: TppSummaryBand;
    ppGroup8: TppGroup;
    ppGroupHeaderBand8: TppGroupHeaderBand;
    ppLabel178: TppLabel;
    ppDBText215: TppDBText;
    ppDBText216: TppDBText;
    ppGroupFooterBand8: TppGroupFooterBand;
    ppLine69: TppLine;
    ppDesignLayers9: TppDesignLayers;
    ppDesignLayer9: TppDesignLayer;
    ppParameterList8: TppParameterList;
    CDSRelChamadoModelo6Rev_Codigo: TIntegerField;
    ppGroup9: TppGroup;
    ppGroupHeaderBand9: TppGroupHeaderBand;
    ppGroupFooterBand9: TppGroupFooterBand;
    ppLabel149: TppLabel;
    ppDBText217: TppDBText;
    ppDBText218: TppDBText;
    ppLine70: TppLine;
    CDSRelChamadoModelo6Tip_Codigo: TIntegerField;
    ppDBCalc7: TppDBCalc;
    CalcHorasJan0601: TppDBCalc;
    lblHora06Jan01: TppLabel;
    lblHora06Fev01: TppLabel;
    CalcHorasFev0601: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppDBCalc13: TppDBCalc;
    ppDBCalc14: TppDBCalc;
    ppDBCalc15: TppDBCalc;
    ppDBCalc16: TppDBCalc;
    ppDBCalc17: TppDBCalc;
    ppDBCalc18: TppDBCalc;
    ppDBCalc19: TppDBCalc;
    ppDBCalc20: TppDBCalc;
    ppDBCalc21: TppDBCalc;
    ppDBCalc22: TppDBCalc;
    lblHora06Mar01: TppLabel;
    lblHora06Abr01: TppLabel;
    lblHora06Mai01: TppLabel;
    lblHora06Jun01: TppLabel;
    lblHora06Jul01: TppLabel;
    lblHora06Ago01: TppLabel;
    lblHora06Set01: TppLabel;
    lblHora06Out01: TppLabel;
    lblHora06Nov01: TppLabel;
    lblHora06Dez01: TppLabel;
    CalcHorasMar0601: TppDBCalc;
    CalcHorasAbr0601: TppDBCalc;
    CalcHorasMai0601: TppDBCalc;
    CalcHorasJun0601: TppDBCalc;
    CalcHorasJul0601: TppDBCalc;
    CalcHorasAgo0601: TppDBCalc;
    CalcHorasSet0601: TppDBCalc;
    CalcHorasOut0601: TppDBCalc;
    CalcHorasNov0601: TppDBCalc;
    CalcHorasDez0601: TppDBCalc;
    ppLabel150: TppLabel;
    ppLabel151: TppLabel;
    ppDBCalc23: TppDBCalc;
    ppDBCalc24: TppDBCalc;
    ppDBCalc25: TppDBCalc;
    ppDBCalc26: TppDBCalc;
    ppDBCalc27: TppDBCalc;
    ppDBCalc28: TppDBCalc;
    ppDBCalc29: TppDBCalc;
    ppDBCalc30: TppDBCalc;
    ppDBCalc31: TppDBCalc;
    ppDBCalc32: TppDBCalc;
    ppDBCalc33: TppDBCalc;
    ppDBCalc34: TppDBCalc;
    lblHora06Jan02: TppLabel;
    lblHora06Fev02: TppLabel;
    lblHora06Mar02: TppLabel;
    lblHora06Abr02: TppLabel;
    lblHora06Mai02: TppLabel;
    lblHora06Jun02: TppLabel;
    lblHora06Jul02: TppLabel;
    lblHora06Ago02: TppLabel;
    lblHora06Set02: TppLabel;
    lblHora06Out02: TppLabel;
    lblHora06Nov02: TppLabel;
    lblHora06Dez02: TppLabel;
    CalcHorasJan0602: TppDBCalc;
    CalcHorasFev0602: TppDBCalc;
    CalcHorasMar0602: TppDBCalc;
    CalcHorasAbr0602: TppDBCalc;
    CalcHorasMai0602: TppDBCalc;
    CalcHorasJun0602: TppDBCalc;
    CalcHorasJul602: TppDBCalc;
    CalcHorasAgo0602: TppDBCalc;
    CalcHorasOut0602: TppDBCalc;
    CalcHorasNov0602: TppDBCalc;
    CalcHorasDez0602: TppDBCalc;
    CalcHorasSet0602: TppDBCalc;
    ppLabel152: TppLabel;
    ppDBCalc35: TppDBCalc;
    ppDBCalc36: TppDBCalc;
    ppDBCalc37: TppDBCalc;
    ppDBCalc38: TppDBCalc;
    ppDBCalc39: TppDBCalc;
    ppDBCalc40: TppDBCalc;
    ppDBCalc41: TppDBCalc;
    ppDBCalc42: TppDBCalc;
    ppDBCalc43: TppDBCalc;
    ppDBCalc44: TppDBCalc;
    ppDBCalc45: TppDBCalc;
    ppDBCalc46: TppDBCalc;
    CalcHorasJan0501: TppDBCalc;
    lblHorasJan0501: TppLabel;
    CalcHorasFev0501: TppDBCalc;
    CalcHorasMar0501: TppDBCalc;
    CalcHorasAbr0501: TppDBCalc;
    CalcHorasMai0501: TppDBCalc;
    CalcHorasJun0501: TppDBCalc;
    CalcHorasJul0501: TppDBCalc;
    CalcHorasAgo0501: TppDBCalc;
    CalcHorasSet0501: TppDBCalc;
    CalcHorasOut0501: TppDBCalc;
    CalcHorasNov0501: TppDBCalc;
    CalcHorasDez0501: TppDBCalc;
    lblHorasFev0501: TppLabel;
    lblHorasMar0501: TppLabel;
    lblHorasAbr0501: TppLabel;
    lblHorasMai0501: TppLabel;
    lblHorasJun0501: TppLabel;
    lblHorasJul0501: TppLabel;
    lblHorasAgo0501: TppLabel;
    lblHorasSet0501: TppLabel;
    lblHorasOut0501: TppLabel;
    lblHorasNov0501: TppLabel;
    lblHorasDez0501: TppLabel;
    ppDBCalc47: TppDBCalc;
    ppLabel92: TppLabel;
    ppDBCalc48: TppDBCalc;
    ppDBCalc49: TppDBCalc;
    ppDBCalc50: TppDBCalc;
    ppDBCalc51: TppDBCalc;
    ppDBCalc52: TppDBCalc;
    ppDBCalc53: TppDBCalc;
    ppDBCalc54: TppDBCalc;
    ppDBCalc55: TppDBCalc;
    ppDBCalc56: TppDBCalc;
    ppDBCalc57: TppDBCalc;
    ppDBCalc58: TppDBCalc;
    lblcha0701: TppLabel;
    lblcha0702: TppLabel;
    lblcha0703: TppLabel;
    lblcha0704: TppLabel;
    lblcha0705: TppLabel;
    lblcha0706: TppLabel;
    lblcha0707: TppLabel;
    lblcha0708: TppLabel;
    lblcha0709: TppLabel;
    lblcha07010: TppLabel;
    lblcha07011: TppLabel;
    lblcha07012: TppLabel;
    CalcHoras0701: TppDBCalc;
    CalcHoras0702: TppDBCalc;
    CalcHoras0703: TppDBCalc;
    CalcHoras0704: TppDBCalc;
    CalcHoras0705: TppDBCalc;
    CalcHoras0706: TppDBCalc;
    CalcHoras0707: TppDBCalc;
    CalcHoras0708: TppDBCalc;
    CalcHoras0709: TppDBCalc;
    CalcHoras07010: TppDBCalc;
    CalcHoras07011: TppDBCalc;
    CalcHoras07012: TppDBCalc;
    CDSRelChamadoModelo8: TClientDataSet;
    CDSRelChamadoModelo8Cli_Perfil: TStringField;
    CDSRelChamadoModelo8QtdeChamados: TIntegerField;
    CDSRelChamadoModelo8TotalHoras: TFloatField;
    CDSRelChamadoModelo8TotalHorasDetalhes: TFloatField;
    CDSRelChamadoModelo8A: TClientDataSet;
    CDSRelChamadoModelo8ACli_Perfil: TStringField;
    CDSRelChamadoModelo8AQtdeChamados: TIntegerField;
    CDSRelChamadoModelo8ATotalHoras: TFloatField;
    CDSRelChamadoModelo8ATotalHorasDetalhes: TFloatField;
    dsRelChamadoModelo8: TDataSource;
    dbRelChamadoModelo8: TppDBPipeline;
    RelChamadoModelo8: TppReport;
    ppHeaderBand9: TppHeaderBand;
    ppLabel93: TppLabel;
    ppSystemVariable25: TppSystemVariable;
    ppSystemVariable26: TppSystemVariable;
    ppLabel94: TppLabel;
    ppLabel95: TppLabel;
    ppLabel96: TppLabel;
    ppLine71: TppLine;
    lblPeriodoModelo8: TppLabel;
    ppLabel98: TppLabel;
    ppSystemVariable27: TppSystemVariable;
    ppDetailBand10: TppDetailBand;
    ppDBText87: TppDBText;
    ppDBText102: TppDBText;
    txtQtdeHorasModelo8: TppDBText;
    lblTotalHorasModelo8: TppLabel;
    txtQtdeHorasColabModelo8: TppDBText;
    lblTotalHorasColabModelo8: TppLabel;
    ppSummaryBand10: TppSummaryBand;
    ppLabel101: TppLabel;
    ppDBCalc59: TppDBCalc;
    ppDBCalc60: TppDBCalc;
    sumTotalHorasModelo8: TppDBCalc;
    lblTotalHorasGeralModelo8: TppLabel;
    ppLine72: TppLine;
    sumTotalHorasColabModelo8: TppDBCalc;
    lblTotalHorasGeralColabModelo8: TppLabel;
    ppDesignLayers10: TppDesignLayers;
    ppDesignLayer10: TppDesignLayer;
    ppParameterList9: TppParameterList;
    CDSRelChamadoModelo8Sum_TotalHoras: TAggregateField;
    ppLabel97: TppLabel;
    lblPerc8: TppLabel;
    RelChamadoModelo9: TppReport;
    ppParameterList10: TppParameterList;
    ppDesignLayers11: TppDesignLayers;
    ppDesignLayer11: TppDesignLayer;
    ppHeaderBand10: TppHeaderBand;
    ppDetailBand11: TppDetailBand;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppLabel102: TppLabel;
    ppLabel103: TppLabel;
    lblPeriodoModelo9: TppLabel;
    ppSystemVariable28: TppSystemVariable;
    ppSystemVariable29: TppSystemVariable;
    ppSystemVariable30: TppSystemVariable;
    ppLine73: TppLine;
    ppSummaryBand11: TppSummaryBand;
    ppLine74: TppLine;
    cdsRelChamadoModelo9: TClientDataSet;
    cdsRelChamadoModelo9ORIGEM: TStringField;
    cdsRelChamadoModelo9Qtde: TIntegerField;
    dsRelChamadoModelo9: TDataSource;
    dbRelChamadoModelo9: TppDBPipeline;
    ppDBText88: TppDBText;
    ppDBText105: TppDBText;
    ppLabel112: TppLabel;
    ppDBCalc61: TppDBCalc;
    cdsRelChamadoModelo9C_QtdeTotal: TAggregateField;
    cdsRelChamadoModelo9C_Percentual: TFloatField;
    ppDBText106: TppDBText;
    ppDBCalc62: TppDBCalc;
    procedure DataModuleCreate(Sender: TObject);
    procedure ppDetailBand3BeforePrint(Sender: TObject);
    procedure ppDetailBand4BeforePrint(Sender: TObject);
    procedure ppDetailBand5BeforePrint(Sender: TObject);
    procedure ppGroupFooterBand2BeforePrint(Sender: TObject);
    procedure ppGroupFooterBand4BeforePrint(Sender: TObject);
    procedure ppSummaryBand2BeforePrint(Sender: TObject);
    procedure ppSummaryBand3BeforePrint(Sender: TObject);
    procedure ppSummaryBand4BeforePrint(Sender: TObject);
    procedure ppSummaryBand5BeforePrint(Sender: TObject);
    procedure ppSummaryBand1BeforePrint(Sender: TObject);
    procedure ppGroupFooterBand1BeforePrint(Sender: TObject);
    procedure CDSRelChamadoModelo6CalcFields(DataSet: TDataSet);
    procedure ppGroupFooterBand8BeforePrint(Sender: TObject);
    procedure ppSummaryBand9BeforePrint(Sender: TObject);
    procedure ppSummaryBand8BeforePrint(Sender: TObject);
    procedure ppSummaryBand7BeforePrint(Sender: TObject);
    procedure ppDetailBand10BeforePrint(Sender: TObject);
    procedure ppSummaryBand10BeforePrint(Sender: TObject);
    procedure cdsRelChamadoModelo9CalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
    procedure ImpressaoModelo3(ADataInicial, ADataFinal, AOrdem: string);
    procedure ImpressaoModelo8(ADataInicial, ADataFinal, AOrdem: string);
    procedure ImpressaoModelo9(ADataInicial, ADataFinal, AOrdem: string);
  end;

var
  DMRelChamado: TDMRelChamado;

implementation

{%CLASSGROUP 'Vcl.Controls.TControl'}

uses uFuncoesSIDomper;

{$R *.dfm}

procedure TDMRelChamado.CDSRelChamadoModelo6CalcFields(DataSet: TDataSet);
begin
  CDSRelChamadoModelo6CTotalHoras1.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas1.AsFloat);
  CDSRelChamadoModelo6CTotalHoras2.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas2.AsFloat);
  CDSRelChamadoModelo6CTotalHoras3.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas3.AsFloat);
  CDSRelChamadoModelo6CTotalHoras4.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas4.AsFloat);
  CDSRelChamadoModelo6CTotalHoras5.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas5.AsFloat);
  CDSRelChamadoModelo6CTotalHoras6.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas6.AsFloat);
  CDSRelChamadoModelo6CTotalHoras7.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas7.AsFloat);
  CDSRelChamadoModelo6CTotalHoras8.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas8.AsFloat);
  CDSRelChamadoModelo6CTotalHoras9.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas9.AsFloat);
  CDSRelChamadoModelo6CTotalHoras10.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas10.AsFloat);
  CDSRelChamadoModelo6CTotalHoras11.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas11.AsFloat);
  CDSRelChamadoModelo6CTotalHoras12.AsString := TFuncoes.DecimalToHora(CDSRelChamadoModelo6Horas12.AsFloat);

end;

procedure TDMRelChamado.cdsRelChamadoModelo9CalcFields(DataSet: TDataSet);
var
  iTotalQtde: Integer;
begin
    try
      iTotalQtde := StrToInt(cdsRelChamadoModelo9C_QtdeTotal.Value);
      cdsRelChamadoModelo9C_Percentual.AsCurrency := (cdsRelChamadoModelo9Qtde.AsInteger / iTotalQtde) * 100;
    except
      cdsRelChamadoModelo9C_Percentual.AsCurrency := 0;
    end;
end;

procedure TDMRelChamado.DataModuleCreate(Sender: TObject);
var
  i: Integer;
begin
  for I := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TClientDataSet then
      TClientDataSet(Components[i]).RemoteServer := dm.DSPConexao;
  end;

  CDSRelChamadoModelo3A.CreateDataSet;
  CDSRelChamadoModelo8A.CreateDataSet;
end;

procedure TDMRelChamado.ImpressaoModelo3(ADataInicial, ADataFinal, AOrdem: string);
begin
  while not CDSRelChamadoModelo3.Eof do
  begin
    if CDSRelChamadoModelo3A.Locate('Usu_Codigo', CDSRelChamadoModelo3Usu_Codigo.AsInteger,[]) then
    begin
      CDSRelChamadoModelo3A.Edit;
      CDSRelChamadoModelo3AQtdeChamados.AsInteger     := CDSRelChamadoModelo3AQtdeChamados.AsInteger + CDSRelChamadoModelo3QtdeChamados.AsInteger;
      CDSRelChamadoModelo3ATotalHoras.AsFloat         := CDSRelChamadoModelo3ATotalHoras.AsFloat + CDSRelChamadoModelo3TotalHoras.AsFloat;
      CDSRelChamadoModelo3ATotalHorasDetalhes.AsFloat := CDSRelChamadoModelo3ATotalHorasDetalhes.AsFloat + CDSRelChamadoModelo3TotalHorasDetalhes.AsFloat;
    end
    else begin
      CDSRelChamadoModelo3A.Append;
      CDSRelChamadoModelo3AUsu_Codigo.AsInteger       := CDSRelChamadoModelo3Usu_Codigo.AsInteger;
      CDSRelChamadoModelo3AQtdeChamados.AsInteger     := CDSRelChamadoModelo3QtdeChamados.AsInteger;
      CDSRelChamadoModelo3ATotalHoras.AsFloat         := CDSRelChamadoModelo3TotalHoras.AsFloat;
      CDSRelChamadoModelo3AUsu_Nome.AsString          := CDSRelChamadoModelo3Usu_Nome.AsString;
      CDSRelChamadoModelo3ATotalHorasDetalhes.AsFloat := CDSRelChamadoModelo3TotalHorasDetalhes.AsFloat;
    end;

    CDSRelChamadoModelo3A.Post;
    CDSRelChamadoModelo3.Next;
  end;

  lblPeriodoModelo3.Caption := 'Período de ' + ADataInicial + ' Até ' + ADataFinal;
  RelChamadoModelo3.Print;
end;

procedure TDMRelChamado.ImpressaoModelo8(ADataInicial, ADataFinal,
  AOrdem: string);
begin
  while not CDSRelChamadoModelo8.Eof do
  begin
    if CDSRelChamadoModelo8A.Locate('Cli_Perfil', CDSRelChamadoModelo8Cli_Perfil.AsString,[]) then
    begin
      CDSRelChamadoModelo8A.Edit;
      CDSRelChamadoModelo8AQtdeChamados.AsInteger     := CDSRelChamadoModelo8AQtdeChamados.AsInteger + CDSRelChamadoModelo8QtdeChamados.AsInteger;
      CDSRelChamadoModelo8ATotalHoras.AsFloat         := CDSRelChamadoModelo8ATotalHoras.AsFloat + CDSRelChamadoModelo8TotalHoras.AsFloat;
      CDSRelChamadoModelo8ATotalHorasDetalhes.AsFloat := CDSRelChamadoModelo8ATotalHorasDetalhes.AsFloat + CDSRelChamadoModelo8TotalHorasDetalhes.AsFloat;
    end
    else begin
      CDSRelChamadoModelo8A.Append;
      CDSRelChamadoModelo8ACli_Perfil.AsString         := CDSRelChamadoModelo8Cli_Perfil.AsString;
      CDSRelChamadoModelo8AQtdeChamados.AsInteger     := CDSRelChamadoModelo8QtdeChamados.AsInteger;
      CDSRelChamadoModelo8ATotalHoras.AsFloat         := CDSRelChamadoModelo8TotalHoras.AsFloat;
      CDSRelChamadoModelo8ATotalHorasDetalhes.AsFloat := CDSRelChamadoModelo8TotalHorasDetalhes.AsFloat;
    end;

    CDSRelChamadoModelo8A.Post;
    CDSRelChamadoModelo8.Next;
  end;

  lblPeriodoModelo8.Caption := 'Período de ' + ADataInicial + ' Até ' + ADataFinal;
  RelChamadoModelo8.Print;

end;

procedure TDMRelChamado.ImpressaoModelo9(ADataInicial, ADataFinal,
  AOrdem: string);
begin
  lblPeriodoModelo9.Caption := 'Período de ' + ADataInicial + ' Até ' + ADataFinal;
  RelChamadoModelo9.Print;
end;

procedure TDMRelChamado.ppDetailBand10BeforePrint(Sender: TObject);
begin
  lblTotalHorasModelo8.Caption := TFuncoes.DecimalToHora(StrToFloatDef(txtQtdeHorasModelo8.Text,0));
  lblTotalHorasColabModelo8.Caption := TFuncoes.DecimalToHora(StrToFloatDef(txtQtdeHorasColabModelo8.Text,0));
  try
    lblPerc8.Caption := FormatFloat(',##0.00', (StrToFloatDef(txtQtdeHorasModelo8.Text,0) / CDSRelChamadoModelo8Sum_TotalHoras.Value) * 100);
  except
    lblPerc8.Caption := '0,00';
  end;
end;

procedure TDMRelChamado.ppDetailBand3BeforePrint(Sender: TObject);
begin
    lblTotalHorasModelo2.Caption := TFuncoes.DecimalToHora(StrToFloatDef(txtQtdeHorasModelo2.Text,0));
end;

procedure TDMRelChamado.ppDetailBand4BeforePrint(Sender: TObject);
begin
  lblTotalHorasModelo3.Caption := TFuncoes.DecimalToHora(StrToFloatDef(txtQtdeHorasModelo3.Text,0));
  lblTotalHorasColabModelo3.Caption := TFuncoes.DecimalToHora(StrToFloatDef(txtQtdeHorasColabModelo3.Text,0));
end;

procedure TDMRelChamado.ppDetailBand5BeforePrint(Sender: TObject);
begin
  lblTotalHorasModelo4.Caption := TFuncoes.DecimalToHora(StrToFloatDef(txtQtdeHorasModelo4.Text,0));
end;

procedure TDMRelChamado.ppGroupFooterBand1BeforePrint(Sender: TObject);
begin
  lblTotalGeralModelo1A.Caption := TFuncoes.DecimalToHora(somaTotalGeralModel1A.Value);
end;

procedure TDMRelChamado.ppGroupFooterBand2BeforePrint(Sender: TObject);
begin
  lblSubTotalHorasModelo2.Caption := TFuncoes.DecimalToHora(sumSubTotalHorasModelo2.Value);
end;

procedure TDMRelChamado.ppGroupFooterBand4BeforePrint(Sender: TObject);
begin
  lblSubTotalHorasModelo4.Caption := TFuncoes.DecimalToHora(sumSubTotalHorasModelo4.Value);
end;

procedure TDMRelChamado.ppGroupFooterBand8BeforePrint(Sender: TObject);
begin
  lblHora06Jan01.Caption := TFuncoes.DecimalToHora(CalcHorasJan0601.Value);
  lblHora06Fev01.Caption := TFuncoes.DecimalToHora(CalcHorasFev0601.Value);
  lblHora06Mar01.Caption := TFuncoes.DecimalToHora(CalcHorasMar0601.Value);
  lblHora06Abr01.Caption := TFuncoes.DecimalToHora(CalcHorasAbr0601.Value);
  lblHora06Mai01.Caption := TFuncoes.DecimalToHora(CalcHorasMai0601.Value);
  lblHora06Jun01.Caption := TFuncoes.DecimalToHora(CalcHorasJun0601.Value);
  lblHora06Jul01.Caption := TFuncoes.DecimalToHora(CalcHorasJul0601.Value);
  lblHora06Ago01.Caption := TFuncoes.DecimalToHora(CalcHorasAgo0601.Value);
  lblHora06Set01.Caption := TFuncoes.DecimalToHora(CalcHorasSet0601.Value);
  lblHora06Out01.Caption := TFuncoes.DecimalToHora(CalcHorasOut0601.Value);
  lblHora06Nov01.Caption := TFuncoes.DecimalToHora(CalcHorasNov0601.Value);
  lblHora06Dez01.Caption := TFuncoes.DecimalToHora(CalcHorasDez0601.Value);
end;

procedure TDMRelChamado.ppSummaryBand10BeforePrint(Sender: TObject);
begin
  lblTotalHorasGeralModelo8.Caption := TFuncoes.DecimalToHora(sumTotalHorasModelo8.Value);
  lblTotalHorasGeralColabModelo8.Caption := TFuncoes.DecimalToHora(sumTotalHorasColabModelo8.Value);
end;

procedure TDMRelChamado.ppSummaryBand1BeforePrint(Sender: TObject);
begin
  lblTotalGeralModelo1.Caption := TFuncoes.DecimalToHora(somaTotalGeralModel1.Value);
end;

procedure TDMRelChamado.ppSummaryBand2BeforePrint(Sender: TObject);
begin
  lblTotalHorasModelo1.Caption := TFuncoes.DecimalToHora(SumTotalHorasModelo1.Value);
end;

procedure TDMRelChamado.ppSummaryBand3BeforePrint(Sender: TObject);
begin
  lblTotalHorasGeralModelo2.Caption := TFuncoes.DecimalToHora(sumTotalHorasModelo2.Value);
end;

procedure TDMRelChamado.ppSummaryBand4BeforePrint(Sender: TObject);
begin
  lblTotalHorasGeralModelo3.Caption := TFuncoes.DecimalToHora(sumTotalHorasModelo3.Value);
  lblTotalHorasGeralColabModelo3.Caption := TFuncoes.DecimalToHora(sumTotalHorasColabModelo3.Value);
end;

procedure TDMRelChamado.ppSummaryBand5BeforePrint(Sender: TObject);
begin
  lblTotalHorasGeralModelo4.Caption := TFuncoes.DecimalToHora(sumTotalHorasModelo4.Value);
end;

procedure TDMRelChamado.ppSummaryBand7BeforePrint(Sender: TObject);
begin
  lblcha0701.Caption := TFuncoes.DecimalToHora(CalcHoras0701.Value);
  lblcha0702.Caption := TFuncoes.DecimalToHora(CalcHoras0702.Value);
  lblcha0703.Caption := TFuncoes.DecimalToHora(CalcHoras0703.Value);
  lblcha0704.Caption := TFuncoes.DecimalToHora(CalcHoras0704.Value);
  lblcha0705.Caption := TFuncoes.DecimalToHora(CalcHoras0705.Value);
  lblcha0706.Caption := TFuncoes.DecimalToHora(CalcHoras0706.Value);
  lblcha0707.Caption := TFuncoes.DecimalToHora(CalcHoras0707.Value);
  lblcha0708.Caption := TFuncoes.DecimalToHora(CalcHoras0708.Value);
  lblcha0709.Caption := TFuncoes.DecimalToHora(CalcHoras0709.Value);
  lblcha07010.Caption := TFuncoes.DecimalToHora(CalcHoras07010.Value);
  lblcha07011.Caption := TFuncoes.DecimalToHora(CalcHoras07011.Value);
  lblcha07012.Caption := TFuncoes.DecimalToHora(CalcHoras07012.Value);

end;

procedure TDMRelChamado.ppSummaryBand8BeforePrint(Sender: TObject);
begin
  lblHorasJan0501.Caption := TFuncoes.DecimalToHora(CalcHorasJan0501.Value);
  lblHorasFev0501.Caption := TFuncoes.DecimalToHora(CalcHorasFev0501.Value);
  lblHorasMar0501.Caption := TFuncoes.DecimalToHora(CalcHorasMar0501.Value);
  lblHorasAbr0501.Caption := TFuncoes.DecimalToHora(CalcHorasAbr0501.Value);
  lblHorasMai0501.Caption := TFuncoes.DecimalToHora(CalcHorasMai0501.Value);
  lblHorasJun0501.Caption := TFuncoes.DecimalToHora(CalcHorasJun0501.Value);
  lblHorasJul0501.Caption := TFuncoes.DecimalToHora(CalcHorasJul0501.Value);
  lblHorasAgo0501.Caption := TFuncoes.DecimalToHora(CalcHorasAgo0501.Value);
  lblHorasSet0501.Caption := TFuncoes.DecimalToHora(CalcHorasSet0501.Value);
  lblHorasOut0501.Caption := TFuncoes.DecimalToHora(CalcHorasOut0501.Value);
  lblHorasNov0501.Caption := TFuncoes.DecimalToHora(CalcHorasNov0501.Value);
  lblHorasDez0501.Caption := TFuncoes.DecimalToHora(CalcHorasDez0501.Value);
end;

procedure TDMRelChamado.ppSummaryBand9BeforePrint(Sender: TObject);
begin
  lblHora06Jan02.Caption := TFuncoes.DecimalToHora(CalcHorasJan0602.Value);
  lblHora06Fev02.Caption := TFuncoes.DecimalToHora(CalcHorasFev0602.Value);
  lblHora06Mar02.Caption := TFuncoes.DecimalToHora(CalcHorasMar0602.Value);
  lblHora06Abr02.Caption := TFuncoes.DecimalToHora(CalcHorasAbr0602.Value);
  lblHora06Mai02.Caption := TFuncoes.DecimalToHora(CalcHorasMai0602.Value);
  lblHora06Jun02.Caption := TFuncoes.DecimalToHora(CalcHorasJun0602.Value);
  lblHora06Jul02.Caption := TFuncoes.DecimalToHora(CalcHorasJul602.Value);
  lblHora06Ago02.Caption := TFuncoes.DecimalToHora(CalcHorasAgo0602.Value);
  lblHora06Set02.Caption := TFuncoes.DecimalToHora(CalcHorasSet0602.Value);
  lblHora06Out02.Caption := TFuncoes.DecimalToHora(CalcHorasOut0602.Value);
  lblHora06Nov02.Caption := TFuncoes.DecimalToHora(CalcHorasNov0602.Value);
  lblHora06Dez02.Caption := TFuncoes.DecimalToHora(CalcHorasDez0602.Value);
end;

end.
